### ISSUE TITLE
Unable to parse style to attribute

### ISSUE THREAD

**Issue by XEngine** [benboba/svg-slim#50]
While optimizing some SVGs with nodeJS I have encountered my several svg files giving style issues.

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <defs>
        <style>.a{fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;}</style>
    </defs>
    <title>3d-box-corner</title>
    <line class="a" x1="12.03" y1="1.5" x2="12.03" y2="6"/>
    <polygon class="a" points="12.03 6 4.03 9.5 12.03 13 20.03 9.5 12.03 6"/>
    <polyline class="a" points="4.03 9.5 4.03 19 12.03 22.5 20.03 19 20.03 9.5"/>
    <line class="a" x1="12.03" y1="13" x2="12.03" y2="22.5"/>
    <line class="a" x1="1.03" y1="20.496" x2="4.03" y2="19"/>
    <line class="a" x1="20.03" y1="19" x2="23" y2="20.482"/>
</svg>
```

If I tried to convert this SVG it converts this into : 

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0,0,24,24"><path d="m12.03,1.5V6m0,0-8,3.5,8,3.5,8-3.5-8-3.5zm-8,3.5V19l8,3.5,8-3.5V9.5m-8,3.5v9.5m-11-2,3-1.5m16,0L23,20.48" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round"/></svg>
```

which is okay, it does the job, converting my <style> into attribute of a single path.
But when I tried to convert this one into a single path svg 

```
<svg id="Light" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <defs>
        <style>.cls-1{fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;}</style>
    </defs>
    <title>multiple-actions-lock</title>
    <g id="_10_23" data-name="10*23">
        <path class="cls-1" d="M7.5,23.5l.5-6h2.5V14a5,5,0,0,0-10,0v3.5H3l.5,6Z"/>
        <circle class="cls-1" cx="5.5" cy="4" r="3.5"/>
    </g>
    <g id="_10_23_-_cut" data-name="10*23 - cut">
        <g id="_Group_" data-name="&lt;Group&gt;">
            <path class="cls-1" d="M17.439,10.37a5.006,5.006,0,0,0-5.561-.9"/>
            <circle class="cls-1" cx="14" cy="4.5" r="3"/>
        </g>
    </g>
    <rect class="cls-1" x="14.5" y="16.5" width="9" height="7" rx="1" ry="1"/>
    <path class="cls-1" d="M19,19a1,1,0,1,0,1,1,1,1,0,0,0-1-1Z"/>
    <path class="cls-1" d="M16.5,16.5V15a2.5,2.5,0,0,1,5,0v1.5"/>
</svg>
```

it gives this error instead of converting it.
```
\dist\index.js:10102
                    dom.styletag.childNodes[0].textContent = cssText;
                                                           ^

TypeError: Cannot set properties of undefined (setting 'textContent')
    at createXML (C:\Users\tidus\Projects\depauli-icons\node_modules\svg-slim\dist\index.js:10102:53)
    at C:\Users\tidus\Projects\depauli-icons\node_modules\svg-slim\dist\index.js:10125:18
```

What I don't understand is they both have the same <defs> <style> tags but one of them is giving issue. I tried to change class name to like the first working example but still giving error.

**Comment by benboba** [comment]
Looks like the style tag was removed by mistake when inside defs , fixed in 2.0.4, thanks for the report

**Comment by XEngine** [comment]
```xml
<svg id="Light" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <defs>
        <style>.cls-1{fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;}</style>
    </defs>
    <title>multiple-actions-lock</title>
    <g id="_10_23" data-name="10*23">
        <path class="cls-1" d="M7.5,23.5l.5-6h2.5V14a5,5,0,0,0-10,0v3.5H3l.5,6Z"/>
        <circle class="cls-1" cx="5.5" cy="4" r="3.5"/>
    </g>
    <g id="_10_23_-_cut" data-name="10*23 - cut">
        <g id="_Group_" data-name="&lt;Group&gt;">
            <path class="cls-1" d="M17.439,10.37a5.006,5.006,0,0,0-5.561-.9"/>
            <circle class="cls-1" cx="14" cy="4.5" r="3"/>
        </g>
    </g>
    <rect class="cls-1" x="14.5" y="16.5" width="9" height="7" rx="1" ry="1"/>
    <path class="cls-1" d="M19,19a1,1,0,1,0,1,1,1,1,0,0,0-1-1Z"/>
    <path class="cls-1" d="M16.5,16.5V15a2.5,2.5,0,0,1,5,0v1.5"/>
</svg>
```

Tested with the 2.0.4 still giving the error; 

```
PS C:\Users\tidus\Projects\depauli-icons> node .\converter.js
C:\Users\tidus\Projects\depauli-icons\node_modules\svg-slim\dist\index.js:10101
                    dom.styletag.childNodes[0].textContent = cssText;
                                                           ^

TypeError: Cannot set properties of undefined (setting 'textContent')
    at createXML (C:\Users\tidus\Projects\depauli-icons\node_modules\svg-slim\dist\index.js:10101:53)
    at C:\Users\tidus\Projects\depauli-icons\node_modules\svg-slim\dist\index.js:10124:18

```

**Comment by benboba** [comment]
O.K. I'll fix this later

**Comment by benboba** [comment]
Done. upd to v2.0.5 pls.
